### ISSUE TITLE
 这是咋回事儿？求解

### ISSUE THREAD

**Issue by will0815** [XiaoMi/open-falcon#47]
./falcon-agent -check
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x73a64e]

goroutine 1 [running]:
github.com/open-falcon/falcon-plus/modules/agent/funcs.DeviceMetrics(0x7f6520, 0xc42010fda0, 0xc42010fca0)
	/home/falcon/gopath/src/github.com/open-falcon/falcon-plus/modules/agent/funcs/dfstat.go:21 +0xfe
github.com/open-falcon/falcon-plus/modules/agent/funcs.CheckCollector()
	/home/falcon/gopath/src/github.com/open-falcon/falcon-plus/modules/agent/funcs/checker.go:21 +0x1f5
main.main()
	/home/falcon/gopath/src/github.com/open-falcon/falcon-plus/modules/agent/main.go:27 +0x1d4

**Comment by laiwei** [comment]
@will0815  

https://github.com/open-falcon/falcon-plus/issues/171

https://github.com/open-falcon/falcon-plus/pull/175

**Comment by will0815** [comment]
ok thx
